name: TypeScript CI
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  checks: write
  pull-requests: write
  contents: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Previous steps remain the same until Save reports...

      - name: Save reports to ci-reports branch
        if: failure()
        run: |
          # Configure git first
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
          PR_NUMBER=$(echo $GITHUB_REF | cut -d'/' -f3)
          REPORT_BRANCH="ci-reports"

          # Create and switch to a temporary branch
          git checkout --orphan temp_$REPORT_BRANCH

          # Clear the working directory except for reports
          git rm -rf --cached .
          find . -mindepth 1 -maxdepth 1 ! -name 'reports' ! -name '.git' -exec rm -rf {} +

          # Create directory structure for this PR
          mkdir -p "pr-$PR_NUMBER/history"

          # Copy the reports with timestamps
          for file in reports/*.txt; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              base="${filename%.*}"
              cp "$file" "pr-$PR_NUMBER/history/${base}-${TIMESTAMP}.txt"
            fi
          done

          # Stage and commit the reports
          git add "pr-$PR_NUMBER/history/"

          # Create commit only if there are changes
          if git status --porcelain | grep .; then
            git commit -m "Add CI reports for PR #${PR_NUMBER} from ${TIMESTAMP} [skip ci]"
          else
            echo "No changes to commit"
            exit 0
          fi

          # Try to push to existing branch or create new one
          if git push origin temp_$REPORT_BRANCH:$REPORT_BRANCH; then
            echo "Pushed to existing branch"
          else
            git push --force origin temp_$REPORT_BRANCH:$REPORT_BRANCH
            echo "Created and pushed new branch"
          fi

      # Rest of the steps remain the same...
