name: TypeScript CI
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  checks: write
  pull-requests: write
  contents: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run tsc
        id: tsc
        run: |
          npm run tsc -- --noEmit > reports/tsc-report.txt 2>&1
          if [ $? -ne 0 ]; then
            echo "TypeScript check failed"
            echo "tsc_failed=true" >> $GITHUB_OUTPUT
            cat reports/tsc-report.txt
          else
            echo "TypeScript check passed"
            echo "tsc_failed=false" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Run ESLint
        id: eslint
        run: |
          npm run lint > reports/lint-report.txt 2>&1
          if [ $? -ne 0 ]; then
            echo "ESLint check failed"
            echo "eslint_failed=true" >> $GITHUB_OUTPUT
            cat reports/lint-report.txt
          else
            echo "ESLint check passed"
            echo "eslint_failed=false" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Upload reports as artifacts
        if: steps.tsc.outputs.tsc_failed == 'true' || steps.eslint.outputs.eslint_failed == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: ci-reports
          path: |
            reports/tsc-report.txt
            reports/lint-report.txt
          retention-days: 14

      - name: Check for failures
        if: steps.tsc.outputs.tsc_failed == 'true' || steps.eslint.outputs.eslint_failed == 'true'
        run: |
          echo "::error::TypeScript or ESLint checks failed. Check the reports for details."
          exit 1

      - name: Comment on PR
        if: steps.tsc.outputs.tsc_failed == 'true' || steps.eslint.outputs.eslint_failed == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tscFailed = '${{ steps.tsc.outputs.tsc_failed }}' === 'true';
            const eslintFailed = '${{ steps.eslint.outputs.eslint_failed }}' === 'true';

            let errorMessage = '❌ CI checks failed:\n\n';
            if (tscFailed) errorMessage += '- TypeScript compilation errors found\n';
            if (eslintFailed) errorMessage += '- ESLint violations found\n';

            errorMessage += '\nPlease check the workflow artifacts for detailed reports.';

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: errorMessage
            });

            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'TypeScript CI',
              head_sha: context.payload.pull_request.head.sha,
              status: 'completed',
              conclusion: 'failure',
              output: {
                title: 'Type checking and linting failed',
                summary: errorMessage
              }
            });

      - name: Create success check
        if: steps.tsc.outputs.tsc_failed != 'true' && steps.eslint.outputs.eslint_failed != 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'TypeScript CI',
              head_sha: context.payload.pull_request.head.sha,
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'All checks passed',
                summary: '✅ TypeScript and ESLint checks passed successfully.'
              }
            });
