name: TypeScript CI
on:
  pull_request:
    types: [opened, synchronize]

# Add this permissions block
permissions:
  checks: write
  pull-requests: write
  contents: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Run tsc
        run: npm run tsc -- --noEmit > tsc-report.txt || true

      - name: Run ESLint
        run: npm run lint > lint-report.txt || true

      - name: Upload tsc report
        uses: actions/upload-artifact@v3
        with:
          name: tsc-report
          path: tsc-report.txt
          if-no-files-found: ignore

      - name: Upload lint report
        uses: actions/upload-artifact@v3
        with:
          name: lint-report
          path: lint-report.txt
          if-no-files-found: ignore

      - name: Set check status
        if: |
          github.event.pull_request.head.repo.full_name == github.repository &&
          (hashFiles('tsc-report.txt') != '' || hashFiles('lint-report.txt') != '')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Type errors or linting violations detected. Please fix before merging.'
            })
            github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'TypeScript CI',
              head_sha: context.payload.pull_request.head.sha,
              status: 'completed',
              conclusion: 'failure',
              output: {
                title: 'Type errors or linting violations',
                summary: 'Please fix type errors and linting violations before merging.'
              }
            })

      - name: Checkout for reports
        if: hashFiles('tsc-report.txt') != '' || hashFiles('lint-report.txt') != ''
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare reports
        if: hashFiles('tsc-report.txt') != '' || hashFiles('lint-report.txt') != ''
        run: |
          mkdir -p reports
          cp tsc-report.txt reports/tsc-report-$(date +"%Y%m%d-%H%M%S").txt
          cp lint-report.txt reports/lint-report-$(date +"%Y%m%d-%H%M%S").txt

      - name: Commit and push report artifacts
        if: hashFiles('tsc-report.txt') != '' || hashFiles('lint-report.txt') != ''
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
